# The URL the site will be built for
base_url = "https://tmahmood.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
#theme = "audrey"
theme = "apollo"
output_dir = "docs"


[markdown]
[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
logo = "logo.png"
menu = [
    { name = "/blog", url = "/blog", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/resume", url = "/resume", weight = 3 },
]
socials = [
    { name = "github", url = "https://github.com/tmahmood/", icon = "github" },
]

title="tmn"
name = "Tarin Mahmood"
homepage = "https://github.com/tmahmood"
footer_links = [{ name = "resume", path = "/resume" }]

[extra.analytics]
enabled = false
